package model

// BuiltinVoices returns the static voice list for the given TTS provider name.
// This replaces the DB-stored voices_json column: voice data is known at compile time
// and does not need to be persisted, seeded, or copied between tenant providers.
func BuiltinVoices(providerName string) []VoiceEntry {
	v, ok := builtinVoiceMap[providerName]
	if !ok {
		return nil
	}
	return v
}

// TTSProviderNames returns the provider names that have builtin voice lists.
// Used by repository queries to filter TTS providers without relying on voices_json.
func TTSProviderNames() []string {
	names := make([]string, 0, len(builtinVoiceMap))
	for k := range builtinVoiceMap {
		names = append(names, k)
	}
	return names
}

// builtinVoiceMap holds all static voice data keyed by provider name.
var builtinVoiceMap = map[string][]VoiceEntry{
	// ── 豆包语音合成 V3 ──────────────────────────────────────────────
	"doubao-speech": {
		{"zh_female_vv_uranus_bigtts", "Vivi 2.0", "female", "adult", 0.92},
		{"zh_female_xiaohe_uranus_bigtts", "小何 2.0", "female", "adult", 0.92},
		{"zh_male_m191_uranus_bigtts", "云舟 2.0", "male", "adult", 0.91},
		{"zh_male_taocheng_uranus_bigtts", "小天 2.0", "male", "adult", 0.91},
		{"zh_male_liufei_uranus_bigtts", "刘飞 2.0", "male", "adult", 0.91},
		{"zh_female_sophie_uranus_bigtts", "魅力苏菲 2.0", "female", "adult", 0.91},
		{"zh_female_qingxinnvsheng_uranus_bigtts", "清新女声 2.0", "female", "adult", 0.91},
		{"zh_female_tianmeixiaoyuan_uranus_bigtts", "甜美小源 2.0", "female", "adult", 0.91},
		{"zh_female_tianmeitaozi_uranus_bigtts", "甜美桃子 2.0", "female", "adult", 0.91},
		{"zh_female_shuangkuaisisi_uranus_bigtts", "爽快思思 2.0", "female", "adult", 0.91},
		{"zh_female_linjianvhai_uranus_bigtts", "邻家女孩 2.0", "female", "adult", 0.91},
		{"zh_male_shaonianzixin_uranus_bigtts", "少年梓辛 2.0", "male", "teen", 0.91},
		{"zh_female_meilinvyou_uranus_bigtts", "魅力女友 2.0", "female", "adult", 0.90},
		{"zh_female_wenroumama_uranus_bigtts", "温柔妈妈 2.0", "female", "adult", 0.90},
		{"zh_female_tvbnv_uranus_bigtts", "TVB女声 2.0", "female", "adult", 0.90},
		{"zh_female_qiaopinv_uranus_bigtts", "俏皮女声 2.0", "female", "adult", 0.90},
		{"zh_male_linjiananhai_uranus_bigtts", "邻家男孩 2.0", "male", "adult", 0.90},
		{"zh_male_jieshuoxiaoming_uranus_bigtts", "解说小明 2.0", "male", "adult", 0.90},
		{"zh_male_yizhipiannan_uranus_bigtts", "译制片男 2.0", "male", "adult", 0.90},
		{"zh_male_ruyaqingnian_uranus_bigtts", "儒雅青年 2.0", "male", "adult", 0.90},
		{"zh_male_wennuanahu_uranus_bigtts", "温暖阿虎 2.0", "male", "adult", 0.90},
		{"zh_male_naiqimengwa_uranus_bigtts", "奶气萌娃 2.0", "male", "child", 0.90},
		{"zh_female_popo_uranus_bigtts", "婆婆 2.0", "female", "elder", 0.90},
		{"zh_female_gaolengyujie_uranus_bigtts", "高冷御姐 2.0", "female", "adult", 0.90},
		{"zh_male_aojiaobazong_uranus_bigtts", "傲娇霸总 2.0", "male", "adult", 0.90},
		{"zh_male_lanyinmianbao_uranus_bigtts", "懒音绵宝 2.0", "male", "adult", 0.90},
		{"zh_male_fanjuanqingnian_uranus_bigtts", "反卷青年 2.0", "male", "adult", 0.90},
		{"zh_female_wenroushunv_uranus_bigtts", "温柔淑女 2.0", "female", "adult", 0.90},
		{"zh_male_huolixiaoge_uranus_bigtts", "活力小哥 2.0", "male", "adult", 0.90},
		{"zh_female_mengyatou_uranus_bigtts", "萌丫头 2.0", "female", "teen", 0.90},
		{"zh_female_tiexinnvsheng_uranus_bigtts", "贴心女声 2.0", "female", "adult", 0.90},
		{"zh_female_jitangmei_uranus_bigtts", "鸡汤妹妹 2.0", "female", "adult", 0.90},
		{"zh_male_cixingjieshuonan_uranus_bigtts", "磁性解说男声 2.0", "male", "adult", 0.90},
		{"zh_male_liangsangmengzai_uranus_bigtts", "亮嗓萌仔 2.0", "male", "child", 0.90},
		{"zh_female_kailangjiejie_uranus_bigtts", "开朗姐姐 2.0", "female", "adult", 0.90},
		{"zh_male_gaolengchenwen_uranus_bigtts", "高冷沉稳 2.0", "male", "adult", 0.90},
		{"zh_male_shenyeboke_uranus_bigtts", "深夜播客 2.0", "male", "adult", 0.90},
		{"zh_female_nvleishen_uranus_bigtts", "女雷神 2.0", "female", "adult", 0.90},
		{"zh_female_qinqienv_uranus_bigtts", "亲切女声 2.0", "female", "adult", 0.90},
		{"zh_male_kuailexiaodong_uranus_bigtts", "快乐小东 2.0", "male", "adult", 0.90},
		{"zh_male_kailangxuezhang_uranus_bigtts", "开朗学长 2.0", "male", "adult", 0.90},
		{"zh_male_youyoujunzi_uranus_bigtts", "悠悠君子 2.0", "male", "adult", 0.90},
		{"zh_female_wenjingmaomao_uranus_bigtts", "文静毛毛 2.0", "female", "adult", 0.90},
		{"zh_female_zhixingnv_uranus_bigtts", "知性女声 2.0", "female", "adult", 0.90},
		{"zh_male_qingshuangnanda_uranus_bigtts", "清爽男大 2.0", "male", "adult", 0.90},
		{"zh_male_yuanboxiaoshu_uranus_bigtts", "渊博小叔 2.0", "male", "adult", 0.90},
		{"zh_male_yangguangqingnian_uranus_bigtts", "阳光青年 2.0", "male", "adult", 0.90},
		{"zh_female_qingchezizi_uranus_bigtts", "清澈梓梓 2.0", "female", "adult", 0.90},
		{"zh_female_tianmeiyueyue_uranus_bigtts", "甜美悦悦 2.0", "female", "adult", 0.90},
		{"zh_female_xinlingjitang_uranus_bigtts", "心灵鸡汤 2.0", "female", "adult", 0.90},
		{"zh_male_wenrouxiaoge_uranus_bigtts", "温柔小哥 2.0", "male", "adult", 0.90},
		{"zh_male_tiancaitongsheng_uranus_bigtts", "天才童声 2.0", "male", "child", 0.90},
		{"zh_male_kailangdidi_uranus_bigtts", "开朗弟弟 2.0", "male", "teen", 0.90},
		{"zh_female_chanmeinv_uranus_bigtts", "谄媚女声 2.0", "female", "adult", 0.90},
		{"zh_female_roumeinvyou_uranus_bigtts", "柔美女友 2.0", "female", "adult", 0.90},
		{"zh_female_wenrouxiaoya_uranus_bigtts", "温柔小雅 2.0", "female", "adult", 0.90},
		{"zh_male_dongfanghaoran_uranus_bigtts", "东方浩然 2.0", "male", "adult", 0.90},
		{"zh_female_shaoergushi_uranus_bigtts", "少儿故事 2.0", "female", "child", 0.90},
		{"zh_male_guanggaojieshuo_uranus_bigtts", "广告解说 2.0", "male", "adult", 0.90},
		{"zh_female_cancan_uranus_bigtts", "知性灿灿 2.0", "female", "adult", 0.90},
		{"zh_female_sajiaoxuemei_uranus_bigtts", "撒娇学妹 2.0", "female", "teen", 0.90},
		{"zh_female_zhishuaiyingzi_uranus_bigtts", "直率英子 2.0", "female", "adult", 0.90},
		{"zh_female_gufengshaoyu_uranus_bigtts", "古风少御 2.0", "female", "adult", 0.90},
		{"zh_male_silang_uranus_bigtts", "四郎 2.0", "male", "adult", 0.90},
		{"zh_male_qingcang_uranus_bigtts", "擎苍 2.0", "male", "adult", 0.90},
		{"zh_male_xionger_uranus_bigtts", "熊二 2.0", "male", "adult", 0.90},
		{"zh_female_yingtaowanzi_uranus_bigtts", "樱桃丸子 2.0", "female", "child", 0.90},
		{"zh_female_wuzetian_uranus_bigtts", "武则天 2.0", "female", "adult", 0.90},
		{"zh_female_gujie_uranus_bigtts", "顾姐 2.0", "female", "adult", 0.90},
		{"zh_male_lubanqihao_uranus_bigtts", "鲁班七号 2.0", "male", "adult", 0.90},
		{"zh_female_linxiao_uranus_bigtts", "林潇 2.0", "female", "adult", 0.90},
		{"zh_female_lingling_uranus_bigtts", "玲玲姐姐 2.0", "female", "adult", 0.90},
		{"zh_female_chunribu_uranus_bigtts", "春日部姐姐 2.0", "female", "adult", 0.90},
		{"zh_male_tangseng_uranus_bigtts", "唐僧 2.0", "male", "adult", 0.90},
		{"zh_male_zhuangzhou_uranus_bigtts", "庄周 2.0", "male", "adult", 0.90},
		{"zh_male_zhubajie_uranus_bigtts", "猪八戒 2.0", "male", "adult", 0.90},
		{"zh_female_ganmaodianyin_uranus_bigtts", "感冒电音姐姐 2.0", "female", "adult", 0.90},
		{"zh_male_baqiqingshu_uranus_bigtts", "霸气青叔 2.0", "male", "adult", 0.90},
		{"zh_female_liuchangnv_uranus_bigtts", "流畅女声 2.0", "female", "adult", 0.90},
		{"zh_male_ruyayichen_uranus_bigtts", "儒雅逸辰 2.0", "male", "adult", 0.90},
		{"zh_female_peiqi_uranus_bigtts", "佩奇猪 2.0", "female", "adult", 0.90},
		{"zh_male_sunwukong_uranus_bigtts", "猴哥 2.0", "male", "adult", 0.90},
		{"zh_female_yingyujiaoxue_uranus_bigtts", "Tina老师 2.0", "female", "adult", 0.90},
		{"zh_female_kefunvsheng_uranus_bigtts", "暖阳女声 2.0", "female", "adult", 0.90},
		{"zh_female_xiaoxue_uranus_bigtts", "儿童绘本 2.0", "female", "child", 0.90},
		{"zh_male_dayi_uranus_bigtts", "大壹 2.0", "male", "adult", 0.90},
		{"zh_female_mizai_uranus_bigtts", "黑猫侦探社咪仔 2.0", "female", "adult", 0.90},
		{"zh_female_jitangnv_uranus_bigtts", "鸡汤女 2.0", "female", "adult", 0.90},
		{"zh_male_xuanyijieshuo_uranus_bigtts", "悬疑解说 2.0", "male", "adult", 0.90},
		{"zh_female_jiaochuannv_uranus_bigtts", "娇喘女声 2.0", "female", "adult", 0.90},
		{"en_male_tim_uranus_bigtts", "Tim", "male", "adult", 0.90},
		{"en_female_dacey_uranus_bigtts", "Dacey", "female", "adult", 0.90},
		{"en_female_stokie_uranus_bigtts", "Stokie", "female", "adult", 0.90},
		// ICL 角色扮演系列（女）
		{"ICL_uranus_zh_female_aojiaonvyou_tob", "傲娇女友 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_aomanjiaosheng_tob", "傲慢娇声 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_xiemeinvwang_tob", "邪魅女王 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_bingjiaojiejie_tob", "病娇姐姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_bingjiaomengmei_tob", "病娇萌妹 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_bingruoshaonv_tob", "病弱少女 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_chengshuwenrou_tob", "成熟温柔 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_chengshujiejie_tob", "成熟姐姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_chunzhenshaonv_tob", "纯真少女 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_chunchenvsheng_tob", "纯澈女生 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_wumeikeren_tob", "妩媚可人 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_guaiqiaokeer_tob", "乖巧可儿 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_heainainai_tob", "和蔼奶奶 2.0", "female", "elder", 0.90},
		{"ICL_uranus_zh_female_huopodiaoman_tob", "活泼刁蛮 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_huoponvhai_tob", "活泼女孩 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_jiaohannvwang_tob", "娇憨女王 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_jiaoruoluoli_tob", "娇弱萝莉 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_jiaxiaozi_tob", "假小子 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_jinglingxiangdao_tob", "精灵向导 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_kailangtingting_tob", "开朗婷婷 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_kaixinxiaohong_tob", "开心小鸿 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_keainvsheng_tob", "可爱女生 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_lingdongxinxin_tob", "灵动欣欣 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_linjuayi_tob", "邻居阿姨 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tianmeijiaoqiao_tob", "甜美娇俏 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_qinglenggaoya_tob", "清冷高雅 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_lixingyuanzi_tob", "理性圆子 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_xingganmeihuo_tob", "性感魅惑 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_nuanxinqianqian_tob", "暖心茜茜 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_nuanxinxuejie_tob", "暖心学姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_qingtianmeimei_tob", "清甜莓莓 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_qingtiantaotao_tob", "清甜桃桃 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_qingxixiaoxue_tob", "清晰小雪 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_qingxinshaonv_tob", "倾心少女 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_rouguhunshi_tob", "柔骨魂师 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_ruanmengtangtang_tob", "软萌糖糖 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_ruanmengtuanzi_tob", "软萌团子 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tianmeihuopo_tob", "甜美活泼 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tianmeixiaoju_tob", "甜美小橘 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tianmeixiaoyu_tob", "甜美小雨 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tiaopigongzhu_tob", "调皮公主 2.0", "female", "teen", 0.90},
		{"ICL_uranus_zh_female_tiexinnvyou_tob", "贴心女友 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_wenrounvshen_tob", "温柔女神 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_wenrouwenya_tob", "温柔文雅 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_zhixinjiejie_tob", "知心姐姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_wumeiyujie_tob", "妩媚御姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_yuanqitianmei_tob", "元气甜妹 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_xiemeiyujie_tob", "邪魅御姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_xingganyujie_tob", "性感御姐 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_xiuliqianqian_tob", "秀丽倩倩 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tiexinguimi_tob", "贴心闺蜜 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_tiexinmeimei_tob", "贴心妹妹 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_wenroubaiyueguang_tob", "温柔白月光 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_chuliannvyou_tob", "初恋女友 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_zhixingwenwan_tob", "知性温婉 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_wenwanshanshan_tob", "温婉珊珊 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_reqingaina_tob", "热情艾娜 2.0", "female", "adult", 0.90},
		{"ICL_uranus_zh_female_qingyingduoduo_tob", "轻盈朵朵 2.0", "female", "adult", 0.90},
		// ICL 角色扮演系列（男）
		{"ICL_uranus_zh_male_aoqilingren_tob", "傲气凌人 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_anrenqinzhu_tob", "黯刃秦主 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_aojiaogongzi_tob", "傲娇公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_aojiaojingying_tob", "傲娇精英 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_aomanqingnian_tob", "傲慢青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_aomanshaoye_tob", "傲慢少爷 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zhenbiandiyu_tob", "枕边低语 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_badaoshaoye_tob", "霸道少爷 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_badaozongcai_tob", "霸道总裁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_bingjiaobailian_tob", "病娇白莲 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_bingjiaodidi_tob", "病娇弟弟 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_bingjiaogege_tob", "病娇哥哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_bingjiaonanyou_tob", "病娇男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_bingjiaoshaonian_tob", "病娇少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_bingruogongzi_tob", "病弱公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_bingruoshaonian_tob", "病弱少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_bujiqingnian_tob", "不羁青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_chunhoudiyin_tob", "醇厚低音 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_paoxiaoxiaoge_tob", "咆哮小哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_yangyang_tob", "炀炀 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_chanruoshaoye_tob", "孱弱少爷 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_chengshuzongcai_tob", "成熟总裁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_chenwenmingzai_tob", "沉稳明仔 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qingyisugan_tob", "清逸苏感 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_chunzhenxuedi_tob", "纯真学弟 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_cixingnansang_tob", "磁性男嗓 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_cujingnansheng_tob", "醋精男生 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_cujingnanyou_tob", "醋精男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_diyinchenyu_tob", "低音沉郁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_fengfashaonian_tob", "风发少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_ruyagongzi_tob", "儒雅公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_fuheigongzi_tob", "腹黑公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_ganjingshaonian_tob", "干净少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_gaolengzongcai_tob", "高冷总裁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_guaogongzi_tob", "孤傲公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_gugaogongzi_tob", "孤高公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_guiyishenmi_tob", "诡异神秘 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_guzhibingjiao_tob", "固执病娇 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_hanhoudunshi_tob", "憨厚敦实 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_huoliqingnian_tob", "活力青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_huoponanyou_tob", "活泼男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_huoposhuanglang_tob", "活泼爽朗 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_huzishushu_tob", "胡子叔叔 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_jijiazhineng_tob", "机甲智能 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_jingyingqingnian_tob", "精英青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_junyigongzi_tob", "俊逸公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_kailangqingkuai_tob", "开朗轻快 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_kailangqingnian_tob", "开朗青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lanyincaohunshi_tob", "蓝银草魂师 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengaozongcai_tob", "冷傲总裁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengdanshuli_tob", "冷淡疏离 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengjungaozhi_tob", "冷峻高智 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengjunshangsi_tob", "冷峻上司 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengkugege_tob", "冷酷哥哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lenglianxiongzhang_tob", "冷脸兄长 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lenglianxueba_tob", "冷脸学霸 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengmonanyou_tob", "冷漠男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lengmoxiongzhang_tob", "冷漠兄长 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lingyunqingnian_tob", "凌云青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qinglengjingui_tob", "清冷矜贵 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_lvchaxiaoge_tob", "绿茶小哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_mengdongqingnian_tob", "懵懂青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_menyoupingxiaoge_tob", "闷油瓶小哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_xiaozhangxiaoge_tob", "嚣张小哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_nianrennanyou_tob", "粘人男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_neiliancaijun_tob", "内敛才俊 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_nuanxintitie_tob", "暖心体贴 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_pianpiangongzi_tob", "翩翩公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_chenwenyouya_tob", "沉稳优雅 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qingsexiaosheng_tob", "青涩小生 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_qingseqingnian_tob", "青涩青年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_qingshuangshaonian_tob", "清爽少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_qingxinbobo_tob", "清新波波 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qinqieqingnian_tob", "亲切青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qinqiexiaozhuo_tob", "亲切小卓 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qinglangwenrun_tob", "清朗温润 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_rexueshaonian_tob", "热血少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_ruyacaijun_tob", "儒雅才俊 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_ruyajunzi_tob", "儒雅君子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_ruyazongcai_tob", "儒雅总裁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_sajiaonansheng_tob", "撒娇男生 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_sajiaonanyou_tob", "撒娇男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_sajiaonianren_tob", "撒娇粘人 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_satuoqingnian_tob", "洒脱青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_shaonianjiangjun_tob", "少年将军 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_shenchenzongcai_tob", "深沉总裁 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_jilingxiaohuo_tob", "机灵小伙 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_shenmifashi_tob", "神秘法师 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_shuaizhenxiaohuo_tob", "率真小伙 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_shuanglangxiaoyang_tob", "爽朗小阳 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_dichenqianquan_tob", "低沉缱绻 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_siwenqingnian_tob", "斯文青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_tianxinanyou_tob", "甜系男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_tiexinnanyou_tob", "贴心男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wenrounantongzhuo_tob", "温柔男同桌 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wenrounanyou_tob", "温柔男友 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wenrouxuezhang_tob", "温柔学长 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wenrunxuezhe_tob", "温润学者 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wenshunshaonian_tob", "温顺少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_guayanxiaoge_tob", "寡言小哥 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_xiaohouye_tob", "小侯爷 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_naiqixiaosheng_tob", "奶气小生 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_xiaosasuixing_tob", "潇洒随性 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wenrouneilian_tob", "温柔内敛 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_xuebanantongzhuo_tob", "学霸男同桌 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_xuebatongzhuo_tob", "学霸同桌 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_yangguangyangyang_tob", "阳光洋洋 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_wennuanshaonian_tob", "温暖少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_yiqishaonian_tob", "意气少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_younidashu_tob", "油腻大叔 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_youmodaye_tob", "幽默大爷 2.0", "male", "elder", 0.90},
		{"ICL_uranus_zh_male_youmoshushu_tob", "幽默叔叔 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_youroubangzhu_tob", "优柔帮主 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_yourougongzi_tob", "优柔公子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_yuanqishaonian_tob", "元气少年 2.0", "male", "teen", 0.90},
		{"ICL_uranus_zh_male_zhangjianjunzi_tob", "仗剑君子 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zhangjianxiake_tob", "仗剑侠客 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zhengzhiqingnian_tob", "正直青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zhishuaiqingnian_tob", "直率青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zhongerqingnian_tob", "中二青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zifuqingnian_tob", "自负青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_zixinqingnian_tob", "自信青年 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_tiancaitongzhuo_tob", "天才同桌 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_qingxinmumu_tob", "清新沐沐 2.0", "male", "adult", 0.90},
		{"ICL_uranus_zh_male_shuanglangshaonian_tob", "爽朗少年 2.0", "male", "teen", 0.90},
		// ICL 角色扮演系列（英文）
		{"ICL_uranus_en_female_charlie_tob", "Charlie 2.0", "female", "adult", 0.90},
		{"ICL_uranus_en_male_ethan_tob", "Ethan 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_alastor_tob", "Alastor 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_chucky_tob", "Chucky 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_noah_tob", "Noah 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_jigsaw_tob", "Jigsaw 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_clown_man_tob", "Clown Man 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_cartoon_chef_tob", "Cartoon Chef 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_frosty_man_tob", "Frosty Man 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_the_grinch_tob", "The Grinch 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_kevin_mccallister_tob", "Kevin McCallister 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_michael_tob", "Michael 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_big_boogie_tob", "Big Boogie 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_xavier_tob", "Xavier 2.0", "male", "adult", 0.90},
		{"ICL_uranus_en_male_zayne_tob", "Zayne 2.0", "male", "adult", 0.90},
	},
	// ── 豆包语音合成 V1 ──────────────────────────────────────────────
	"doubao-speech-v1": {
		{"BV001_streaming", "通用女声", "female", "adult", 0.82},
		{"BV002_streaming", "通用男声", "male", "adult", 0.82},
		{"BV005_streaming", "活泼女声", "female", "teen", 0.83},
		{"BV006_streaming", "沉稳男声", "male", "adult", 0.83},
		{"BV007_streaming", "新闻女声", "female", "adult", 0.84},
		{"BV033_streaming", "温柔小哥", "male", "adult", 0.84},
		{"BV034_streaming", "知性女声", "female", "adult", 0.84},
		{"zh_female_shuangkuaisisi_moon_bigtts", "爽快思思", "female", "adult", 0.90},
		{"zh_male_jingqiangkanye_moon_bigtts", "精英男声", "male", "adult", 0.90},
		{"zh_female_linjingzhu_moon_bigtts", "甜美女声", "female", "adult", 0.90},
		{"zh_male_chunhou_moon_bigtts", "醇厚男声", "male", "adult", 0.90},
		{"zh_female_wanqingxiaochun_moon_bigtts", "温情晓春", "female", "adult", 0.90},
		{"zh_male_zhubo_moon_bigtts", "主播男声", "male", "adult", 0.90},
		{"en_female_sarah_stream", "Sarah（英文女声）", "female", "adult", 0.85},
		{"en_male_adam_stream", "Adam（英文男声）", "male", "adult", 0.85},
	},
	// ── 百度语音合成 ──────────────────────────────────────────────────
	"baidu-tts": {
		{"0", "度小美（标准女声）", "female", "adult", 0.85},
		{"1", "度小宇（标准男声）", "male", "adult", 0.85},
		{"3", "度逍遥（情感男声/磁性）", "male", "adult", 0.87},
		{"4", "度丫丫（情感童声/女）", "female", "child", 0.85},
		{"5", "度小娇（情感女声）", "female", "adult", 0.87},
		{"103", "度米朵（精品童声/女）", "female", "child", 0.88},
		{"106", "度博文（精品情感男声）", "male", "adult", 0.88},
		{"110", "度小童（精品童声/男）", "male", "child", 0.88},
		{"111", "度小萌（精品童声/女）", "female", "child", 0.88},
	},
	// ── MiniMax 语音合成 ──────────────────────────────────────────────
	"minimax-tts": {
		{"female-shaonv", "少女音（年轻女/活泼）", "female", "teen", 0.91},
		{"female-yujie", "御姐音（成熟女/知性）", "female", "adult", 0.91},
		{"female-tianmei", "甜美音（女/甜蜜）", "female", "adult", 0.90},
		{"female-qingxin", "清新音（女/清新）", "female", "adult", 0.90},
		{"male-qn-qingse", "青涩青年音（男/年轻）", "male", "teen", 0.91},
		{"male-qn-jingying", "精英青年音（男/知性）", "male", "adult", 0.91},
		{"male-qn-badao", "霸道青年音（男/有力）", "male", "adult", 0.90},
		{"male-qn-daxuesheng", "大学生音（男/活力）", "male", "teen", 0.90},
		{"presenter_male", "男主持（专业）", "male", "adult", 0.91},
		{"presenter_female", "女主持（专业）", "female", "adult", 0.91},
		{"audiobook_male_1", "有声书男声1", "male", "adult", 0.92},
		{"audiobook_male_2", "有声书男声2", "male", "adult", 0.92},
		{"audiobook_female_1", "有声书女声1", "female", "adult", 0.92},
		{"audiobook_female_2", "有声书女声2", "female", "adult", 0.92},
		{"male-story", "故事男声（儿童）", "male", "child", 0.90},
		{"female-story", "故事女声（儿童）", "female", "child", 0.90},
	},
	// ── 阿里云 CosyVoice + 千问 TTS ────────────────────────────────────
	"qianwen": {
		// CosyVoice v3-flash
		{"longanyang", "龙安洋（男/阳光社交）", "male", "adult", 0.94},
		{"longanhuan_v3", "龙安欢V3（女/欢脱元气）", "female", "adult", 0.94},
		{"longanhuan", "龙安欢（女/欢脱元气）", "female", "adult", 0.93},
		{"longhuhu_v3", "龙呼呼（女童/天真烂漫）", "female", "child", 0.93},
		{"longpaopao_v3", "龙泡泡V3（飞天泡泡音）", "neutral", "child", 0.91},
		{"longjielidou_v3", "龙杰力豆V3（男童/阳光顽皮）", "male", "child", 0.91},
		{"longxian_v3", "龙仙V3（女/豪放可爱）", "female", "child", 0.91},
		{"longling_v3", "龙铃V3（女/稚气呆板）", "female", "child", 0.91},
		{"longshanshan_v3", "龙闪闪V3（戏剧化童声）", "neutral", "child", 0.91},
		{"longniuniu_v3", "龙牛牛V3（阳光男童声）", "male", "child", 0.91},
		{"longjiaxin_v3", "龙嘉欣V3（女/粤语优雅）", "female", "adult", 0.92},
		{"longjiayi_v3", "龙嘉怡V3（女/知性粤语）", "female", "adult", 0.92},
		{"longanyue_v3", "龙安粤V3（男/欢脱粤语）", "male", "adult", 0.92},
		{"longlaotie_v3", "龙老铁V3（男/东北直率）", "male", "adult", 0.92},
		{"longshange_v3", "龙陕哥V3（男/原味陕北）", "male", "adult", 0.92},
		{"longanmin_v3", "龙安闽V3（女/清纯闽南）", "female", "adult", 0.92},
		{"loongkyong_v3", "loongkyong V3（韩语女）", "female", "adult", 0.90},
		{"loongriko_v3", "Riko V3（二次元日语女）", "female", "teen", 0.90},
		{"loongtomoka_v3", "loongtomoka V3（日语女）", "female", "adult", 0.90},
		{"loongabby_v3", "loongabby V3（美式英语女）", "female", "adult", 0.90},
		{"loongandy_v3", "loongandy V3（美式英语男）", "male", "adult", 0.90},
		{"loongannie_v3", "loongannie V3（美式英语女）", "female", "adult", 0.90},
		{"loongava_v3", "loongava V3（美式英语女）", "female", "adult", 0.90},
		{"loongbeth_v3", "loongbeth V3（美式英语女）", "female", "adult", 0.90},
		{"loongbetty_v3", "loongbetty V3（美式英语女）", "female", "adult", 0.90},
		{"loongcally_v3", "loongcally V3（美式英语女）", "female", "adult", 0.90},
		{"loongcindy_v3", "loongcindy V3（美式英语女）", "female", "adult", 0.90},
		{"loongdavid_v3", "loongdavid V3（美式英语男）", "male", "adult", 0.90},
		{"loongdonna_v3", "loongdonna V3（美式英语女）", "female", "adult", 0.90},
		{"loongemily_v3", "loongemily V3（英式英语女）", "female", "adult", 0.90},
		{"loongeric_v3", "loongeric V3（英式英语男）", "male", "adult", 0.90},
		{"loongluna_v3", "loongluna V3（英式英语女）", "female", "adult", 0.90},
		{"loongluca_v3", "loongluca V3（英式英语男）", "male", "adult", 0.90},
		{"loongtomoya_v3", "loongtomoya V3（日语男）", "male", "adult", 0.90},
		{"loongyuuna_v3", "Yuuna V3（日语女）", "female", "teen", 0.90},
		{"loongyuuma_v3", "Yuuma V3（日语男）", "male", "teen", 0.90},
		{"loongjihun_v3", "Jihun V3（韩语男）", "male", "adult", 0.90},
		{"loongindah_v3", "loongindah V3（印尼语女）", "female", "adult", 0.90},
		{"longfei_v3", "龙飞V3（男/热血磁性）", "male", "adult", 0.92},
		{"longyingxiao_v3", "龙应笑V3（女/清甜推销）", "female", "adult", 0.91},
		{"longyingxun_v3", "龙应询V3（男/年轻青涩）", "male", "adult", 0.91},
		{"longyingjing_v3", "龙应静V3（女/低调冷静）", "female", "adult", 0.91},
		{"longyingling_v3", "龙应聆V3（女/温和共情）", "female", "adult", 0.91},
		{"longyingtao_v3", "龙应桃V3（女/温柔淡定）", "female", "adult", 0.91},
		{"longxiaochun_v3", "龙小淳V3（女/知性语音助手）", "female", "adult", 0.93},
		{"longxiaoxia_v3", "龙小夏V3（女/沉稳权威）", "female", "adult", 0.93},
		{"longyumi_v3", "YUMI V3（女/正经青年）", "female", "adult", 0.93},
		{"longanyun_v3", "龙安昀V3（男/居家暖男）", "male", "adult", 0.92},
		{"longanwen_v3", "龙安温V3（女/优雅知性）", "female", "adult", 0.92},
		{"longanli_v3", "龙安莉V3（女/利落从容）", "female", "adult", 0.92},
		{"longanlang_v3", "龙安朗V3（男/清爽利落）", "male", "adult", 0.92},
		{"longyingmu_v3", "龙应沐V3（女/优雅知性）", "female", "adult", 0.91},
		{"longantai_v3", "龙安台V3（女/嗲甜台湾）", "female", "adult", 0.91},
		{"longhua_v3", "龙华V3（女/元气甜美）", "female", "adult", 0.91},
		{"longcheng_v3", "龙橙V3（男/智慧青年）", "male", "adult", 0.91},
		{"longze_v3", "龙泽V3（男/温暖元气）", "male", "adult", 0.91},
		{"longzhe_v3", "龙哲V3（男/呆板大暖男）", "male", "adult", 0.91},
		{"longyan_v3", "龙颜V3（女/温暖春风）", "female", "adult", 0.91},
		{"longxing_v3", "龙星V3（女/温婉邻家）", "female", "adult", 0.91},
		{"longtian_v3", "龙天V3（男/磁性理智）", "male", "adult", 0.91},
		{"longwan_v3", "龙婉V3（女/细腻柔声）", "female", "adult", 0.91},
		{"longqiang_v3", "龙嫱V3（女/浪漫风情）", "female", "adult", 0.91},
		{"longfeifei_v3", "龙菲菲V3（女/甜美娇气）", "female", "adult", 0.91},
		{"longhao_v3", "龙浩V3（男/多情忧郁）", "male", "adult", 0.91},
		{"longanrou_v3", "龙安柔V3（女/温柔闺蜜）", "female", "adult", 0.91},
		{"longhan_v3", "龙寒V3（男/温暖痴情）", "male", "adult", 0.91},
		{"longanzhi_v3", "龙安智V3（男/睿智轻熟）", "male", "adult", 0.91},
		{"longanling_v3", "龙安灵V3（女/思维灵动）", "female", "adult", 0.91},
		{"longanya_v3", "龙安雅V3（女/高雅气质）", "female", "adult", 0.91},
		{"longanqin_v3", "龙安亲V3（女/亲和活泼）", "female", "adult", 0.91},
		{"longmiao_v3", "龙妙V3（女/抑扬顿挫）", "female", "adult", 0.93},
		{"longsanshu_v3", "龙三叔V3（男/沉稳有声书）", "male", "adult", 0.93},
		{"longyuan_v3", "龙媛V3（女/温暖治愈）", "female", "adult", 0.92},
		{"longyue_v3", "龙悦V3（女/温暖磁性）", "female", "adult", 0.92},
		{"longxiu_v3", "龙修V3（男/博才说书）", "male", "adult", 0.92},
		{"longnan_v3", "龙楠V3（男/睿智青年）", "male", "adult", 0.92},
		{"longwanjun_v3", "龙婉君V3（女/细腻柔声）", "female", "adult", 0.92},
		{"longyichen_v3", "龙逸尘V3（男/洒脱活力）", "male", "adult", 0.92},
		{"longlaobo_v3", "龙老伯V3（男/沧桑岁月）", "male", "elder", 0.91},
		{"longlaoyi_v3", "龙老姨V3（女/烟火从容）", "female", "elder", 0.91},
		{"longjiqi_v3", "龙机器V3（呆萌机器人）", "neutral", "adult", 0.91},
		{"longhouge_v3", "龙猴哥V3（经典猴哥）", "male", "adult", 0.91},
		{"longdaiyu_v3", "龙黛玉V3（娇率才女）", "female", "teen", 0.91},
		{"longanran_v3", "龙安燃V3（女/活泼直播）", "female", "adult", 0.92},
		{"longanxuan_v3", "龙安宣V3（女/经典直播）", "female", "adult", 0.92},
		{"longshuo_v3", "龙硕V3（男/干练播报）", "male", "adult", 0.93},
		{"longshu_v3", "龙书V3（男/沉稳播报）", "male", "adult", 0.93},
		{"loongbella_v3", "Bella 3.0（女/中英双语）", "female", "adult", 0.93},
		// CosyVoice v2
		{"longyingxiao", "龙应笑（女/清甜推销）", "female", "adult", 0.91},
		{"longjiqi", "龙机器（呆萌机器人）", "neutral", "adult", 0.91},
		{"longhouge", "龙猴哥（经典猴哥）", "male", "adult", 0.91},
		{"longjixin", "龙机心（女/毒舌心机）", "female", "adult", 0.91},
		{"longanyue", "龙安粤（男/欢脱粤语）", "male", "adult", 0.91},
		{"longshange", "龙陕哥（男/原味陕北）", "male", "adult", 0.91},
		{"longanmin", "龙安敏（女/甜美闽南）", "female", "adult", 0.91},
		{"longdaiyu", "龙黛玉（娇率才女）", "female", "teen", 0.91},
		{"longgaoseng", "龙高僧（男/得道高僧）", "male", "elder", 0.91},
		{"longanli", "龙安莉（女/利落从容）", "female", "adult", 0.91},
		{"longanlang", "龙安朗（男/清爽利落）", "male", "adult", 0.91},
		{"longanwen", "龙安温（女/优雅知性）", "female", "adult", 0.91},
		{"longanyun", "龙安昀（男/居家暖男）", "male", "adult", 0.91},
		{"longyumi_v2", "YUMI V2（女/正经青年）", "female", "adult", 0.91},
		{"longxiaochun_v2", "龙小淳V2（女/知性积极）", "female", "adult", 0.91},
		{"longxiaoxia_v2", "龙小夏V2（女/沉稳权威）", "female", "adult", 0.91},
		{"longyichen", "龙逸尘（男/洒脱活力）", "male", "adult", 0.91},
		{"longwanjun", "龙婉君（女/细腻柔声）", "female", "adult", 0.91},
		{"longlaobo", "龙老伯（男/沧桑岁月）", "male", "elder", 0.91},
		{"longlaoyi", "龙老姨（女/烟火从容）", "female", "elder", 0.91},
		{"longbaizhi", "龙白芷（女/睿气旁白）", "female", "adult", 0.91},
		{"longsanshu", "龙三叔（男/沉稳有声书）", "male", "adult", 0.91},
		{"longxiu_v2", "龙修V2（男/博才说书）", "male", "adult", 0.91},
		{"longmiao_v2", "龙妙V2（女/抑扬顿挫）", "female", "adult", 0.91},
		{"longyue_v2", "龙悦V2（女/温暖磁性）", "female", "adult", 0.91},
		{"longnan_v2", "龙楠V2（男/睿智青年）", "male", "adult", 0.91},
		{"longyuan_v2", "龙媛V2（女/温暖治愈）", "female", "adult", 0.91},
		{"longanqin", "龙安亲（女/亲和活泼）", "female", "adult", 0.91},
		{"longanya", "龙安雅（女/高雅气质）", "female", "adult", 0.91},
		{"longanshuo", "龙安朔（男/干净清爽）", "male", "adult", 0.91},
		{"longanling", "龙安灵（女/思维灵动）", "female", "adult", 0.91},
		{"longanzhi", "龙安智（男/睿智轻熟）", "male", "adult", 0.91},
		{"longanrou", "龙安柔（女/温柔闺蜜）", "female", "adult", 0.91},
		{"longqiang_v2", "龙嫱V2（女/浪漫风情）", "female", "adult", 0.91},
		{"longhan_v2", "龙寒V2（男/温暖痴情）", "male", "adult", 0.91},
		{"longxing_v2", "龙星V2（女/温婉邻家）", "female", "adult", 0.91},
		{"longhua_v2", "龙华V2（女/元气甜美）", "female", "adult", 0.91},
		{"longwan_v2", "龙婉V2（女/积极知性）", "female", "adult", 0.91},
		{"longcheng_v2", "龙橙V2（男/智慧青年）", "male", "adult", 0.91},
		{"longfeifei_v2", "龙菲菲V2（女/甜美娇气）", "female", "adult", 0.91},
		{"longxiaocheng_v2", "龙小诚V2（男/磁性低音）", "male", "adult", 0.91},
		{"longzhe_v2", "龙哲V2（男/呆板大暖男）", "male", "adult", 0.91},
		{"longyan_v2", "龙颜V2（女/温暖春风）", "female", "adult", 0.91},
		{"longtian_v2", "龙天V2（男/磁性理智）", "male", "adult", 0.91},
		{"longze_v2", "龙泽V2（男/温暖元气）", "male", "adult", 0.91},
		{"longshao_v2", "龙邵V2（男/积极向上）", "male", "adult", 0.91},
		{"longhao_v2", "龙浩V2（男/多情忧郁）", "male", "adult", 0.91},
		{"kabuleshen_v2", "龙深V2（男/实力歌手）", "male", "adult", 0.91},
		{"longhuhu", "龙呼呼（女童/天真烂漫）", "female", "child", 0.91},
		{"longanpei", "龙安培（女/青少年教师）", "female", "adult", 0.91},
		{"longwangwang", "龙汪汪（台湾少年音）", "neutral", "child", 0.90},
		{"longpaopao", "龙泡泡（飞天泡泡音）", "neutral", "child", 0.90},
		{"longshanshan", "龙闪闪（戏剧化童声）", "neutral", "child", 0.90},
		{"longniuniu", "龙牛牛（阳光男童声）", "male", "child", 0.90},
		{"longyingmu", "龙应沐（女/优雅知性）", "female", "adult", 0.91},
		{"longyingxun", "龙应询（男/年轻青涩）", "male", "adult", 0.91},
		{"longyingcui", "龙应催（男/严肃催收）", "male", "adult", 0.90},
		{"longyingda", "龙应答（女/开朗高音）", "female", "adult", 0.90},
		{"longyingjing", "龙应静（女/低调冷静）", "female", "adult", 0.91},
		{"longyingyan", "龙应严（女/义正严辞）", "female", "adult", 0.90},
		{"longyingtian", "龙应甜（女/温柔甜美）", "female", "adult", 0.91},
		{"longyingbing", "龙应冰（女/尖锐强势）", "female", "adult", 0.90},
		{"longyingtao", "龙应桃（女/温柔淡定）", "female", "adult", 0.91},
		{"longyingling", "龙应聆（女/温和共情）", "female", "adult", 0.91},
		{"longanran", "龙安燃（女/活泼直播）", "female", "adult", 0.91},
		{"longanxuan", "龙安宣（女/经典直播）", "female", "adult", 0.91},
		{"longanchong", "龙安冲（男/激情推销）", "male", "adult", 0.91},
		{"longanping", "龙安萍（女/高亢直播）", "female", "adult", 0.90},
		{"longjielidou_v2", "龙杰力豆V2（男童/阳光顽皮）", "male", "child", 0.90},
		{"longling_v2", "龙铃V2（女/稚气呆板）", "female", "child", 0.90},
		{"longke_v2", "龙可V2（女/懵懂乖乖）", "female", "child", 0.90},
		{"longxian_v2", "龙仙V2（女/豪放可爱）", "female", "child", 0.90},
		{"longlaotie_v2", "龙老铁V2（男/东北直率）", "male", "adult", 0.91},
		{"longjiayi_v2", "龙嘉怡V2（女/知性粤语）", "female", "adult", 0.91},
		{"longtao_v2", "龙桃V2（女/积极粤语）", "female", "adult", 0.91},
		{"longfei_v2", "龙飞V2（男/热血磁性）", "male", "adult", 0.91},
		{"libai_v2", "李白V2（男/古代诗仙）", "male", "adult", 0.91},
		{"longjin_v2", "龙津V2（男/优雅温润）", "male", "adult", 0.91},
		{"longshu_v2", "龙书V2（男/沉稳播报）", "male", "adult", 0.91},
		{"loongbella_v2", "Bella 2.0（女/精准干练）", "female", "adult", 0.91},
		{"longshuo_v2", "龙硕V2（男/博才干练）", "male", "adult", 0.91},
		{"longxiaobai_v2", "龙小白V2（女/沉稳播报）", "female", "adult", 0.91},
		{"longjing_v2", "龙婧V2（女/典型播音）", "female", "adult", 0.91},
		{"loongstella_v2", "Stella V2（女/飒爽利落）", "female", "adult", 0.91},
		{"loongyuuna_v2", "loongyuuna V2（日语女）", "female", "adult", 0.90},
		{"loongyuuma_v2", "loongyuuma V2（日语男）", "male", "adult", 0.90},
		{"loongjihun_v2", "loongjihun V2（韩语男）", "male", "adult", 0.90},
		{"loongeva_v2", "loongeva V2（英式英语女）", "female", "adult", 0.90},
		{"loongbrian_v2", "loongbrian V2（英式英语男）", "male", "adult", 0.90},
		{"loongluna_v2", "loongluna V2（英式英语女）", "female", "adult", 0.90},
		{"loongluca_v2", "loongluca V2（英式英语男）", "male", "adult", 0.90},
		{"loongemily_v2", "loongemily V2（英式英语女）", "female", "adult", 0.90},
		{"loongeric_v2", "loongeric V2（英式英语男）", "male", "adult", 0.90},
		{"loongabby_v2", "loongabby V2（美式英语女）", "female", "adult", 0.90},
		{"loongannie_v2", "loongannie V2（美式英语女）", "female", "adult", 0.90},
		{"loongandy_v2", "loongandy V2（美式英语男）", "male", "adult", 0.90},
		{"loongava_v2", "loongava V2（美式英语女）", "female", "adult", 0.90},
		{"loongbeth_v2", "loongbeth V2（美式英语女）", "female", "adult", 0.90},
		{"loongbetty_v2", "loongbetty V2（美式英语女）", "female", "adult", 0.90},
		{"loongcindy_v2", "loongcindy V2（美式英语女）", "female", "adult", 0.90},
		{"loongcally_v2", "loongcally V2（美式英语女）", "female", "adult", 0.90},
		{"loongdavid_v2", "loongdavid V2（美式英语男）", "male", "adult", 0.90},
		{"loongdonna_v2", "loongdonna V2（美式英语女）", "female", "adult", 0.90},
		{"loongkyong_v2", "loongkyong V2（韩语女）", "female", "adult", 0.90},
		{"loongtomoka_v2", "loongtomoka V2（日语女）", "female", "adult", 0.90},
		{"loongtomoya_v2", "loongtomoya V2（日语男）", "male", "adult", 0.90},
		// CosyVoice v1
		{"longwan", "龙婉（女/甜美温柔）", "female", "adult", 0.90},
		{"longcheng", "龙橙（男/清晰专业）", "male", "adult", 0.90},
		{"longhua", "龙华（男/成熟稳重）", "male", "adult", 0.90},
		{"longxiaochun", "龙小淳（女/知性温暖）", "female", "adult", 0.90},
		{"longxiaoxia", "龙晓夏（女/活泼朝气）", "female", "adult", 0.90},
		{"longxiaocheng", "龙小诚（男/磁性低音）", "male", "adult", 0.90},
		{"longxiaobai", "龙小白（男/年轻开朗）", "male", "adult", 0.90},
		{"longlaotie", "龙老铁（男/东北话）", "male", "adult", 0.90},
		{"longshu", "龙叔（男/叙述沉稳）", "male", "adult", 0.90},
		{"longshuo", "龙硕（男/播报）", "male", "adult", 0.90},
		{"longjing", "龙婧（女/播音）", "female", "adult", 0.90},
		{"longmiao", "龙妙（女/有声书）", "female", "adult", 0.90},
		{"longyue", "龙悦（女/温暖磁性）", "female", "adult", 0.90},
		{"longyuan", "龙媛（女/有声书）", "female", "adult", 0.90},
		{"longfei", "龙飞（男/沉稳自信）", "male", "adult", 0.90},
		{"longjielidou", "龙杰力豆（儿童/新闻播报）", "neutral", "child", 0.90},
		{"longtong", "龙彤（女/导航播报）", "female", "adult", 0.90},
		{"longxiang", "龙祥（男/磁性低沉）", "male", "adult", 0.90},
		{"loongstella", "Stella（女/飒爽利落）", "female", "adult", 0.90},
		{"loongbella", "Bella（女/精准干练）", "female", "adult", 0.90},
		// 千问 TTS 音色
		{"Cherry", "Cherry 芊悦（女/阳光亲切）", "female", "adult", 0.92},
		{"Serena", "Serena 苏瑶（女/温柔）", "female", "adult", 0.92},
		{"Ethan", "Ethan 晨煦（男/阳光活力）", "male", "adult", 0.91},
		{"Chelsie", "Chelsie 千雪（女/二次元虚拟女友）", "female", "teen", 0.91},
		{"Momo", "Momo 茉兔（女/撒娇搞怪）", "female", "teen", 0.91},
		{"Vivian", "Vivian 十三（女/拽拽可爱）", "female", "teen", 0.91},
		{"Moon", "Moon 月白（男/率性帅气）", "male", "teen", 0.91},
		{"Maia", "Maia 四月（女/知性温柔）", "female", "adult", 0.91},
		{"Kai", "Kai 凯（男/耳朵SPA）", "male", "adult", 0.91},
		{"Nofish", "Nofish 不吃鱼（男/无翘舌）", "male", "adult", 0.90},
		{"Bella", "Bella 萌宝（女童/小萝莉）", "female", "child", 0.91},
		{"Eldric Sage", "Eldric Sage 沧明子（男/沉稳睿智老者）", "male", "elder", 0.91},
		{"Mia", "Mia 乖小妹（女/温顺乖巧）", "female", "adult", 0.91},
		{"Mochi", "Mochi 沙小弥（男童/聪明早慧）", "male", "child", 0.91},
		{"Bellona", "Bellona 燕铮莺（女/洪亮江湖）", "female", "adult", 0.91},
		{"Vincent", "Vincent 田叔（男/沙哑烟嗓）", "male", "adult", 0.91},
		{"Bunny", "Bunny 萌小姬（女童/萌萝莉）", "female", "child", 0.91},
		{"Neil", "Neil 阿闻（男/新闻主持）", "male", "adult", 0.91},
		{"Elias", "Elias 墨讲师（女/知识讲解）", "female", "adult", 0.91},
		{"Arthur", "Arthur 徐大爷（男/质朴老者）", "male", "elder", 0.91},
		{"Nini", "Nini 邻家妹妹（女/甜糯少女）", "female", "teen", 0.91},
		{"Seren", "Seren 小婉（女/温和助眠）", "female", "adult", 0.91},
		{"Pip", "Pip 顽屁小孩（男童/调皮童真）", "male", "child", 0.91},
		{"Stella", "Stella 少女阿月（女/迷糊少女）", "female", "teen", 0.91},
		{"Jennifer", "Jennifer 詹妮弗（女/电影质感美语）", "female", "adult", 0.92},
		{"Ryan", "Ryan 甜茶（男/戏感炸裂）", "male", "adult", 0.91},
		{"Katerina", "Katerina 卡捷琳娜（女/御姐）", "female", "adult", 0.91},
		{"Aiden", "Aiden 艾登（男/美语大男孩）", "male", "adult", 0.91},
		{"Bodega", "Bodega 博德加（男/热情西班牙）", "male", "adult", 0.90},
		{"Sonrisa", "Sonrisa 索尼莎（女/热情拉美）", "female", "adult", 0.90},
		{"Alek", "Alek 阿列克（男/俄式冷暖）", "male", "adult", 0.90},
		{"Dolce", "Dolce 多尔切（男/慵懒意大利）", "male", "adult", 0.90},
		{"Sohee", "Sohee 素熙（女/温柔韩国欧尼）", "female", "adult", 0.90},
		{"Ono Anna", "Ono Anna 小野杏（女/鬼灵精怪日语）", "female", "teen", 0.90},
		{"Lenn", "Lenn 莱恩（男/德国叛逆青年）", "male", "teen", 0.90},
		{"Emilien", "Emilien 埃米尔安（男/浪漫法国）", "male", "adult", 0.90},
		{"Andre", "Andre 安德雷（男/磁性沉稳）", "male", "adult", 0.91},
		{"Radio Gol", "Radio Gol 拉迪奥·戈尔（男/足球解说）", "male", "adult", 0.90},
		{"Jada", "Jada 上海-阿珍（女/上海话）", "female", "adult", 0.90},
		{"Dylan", "Dylan 北京-晓东（男/北京话）", "male", "teen", 0.90},
		{"Li", "Li 南京-老李（男/南京话）", "male", "adult", 0.90},
		{"Marcus", "Marcus 陕西-秦川（男/陕西话）", "male", "adult", 0.90},
		{"Roy", "Roy 闽南-阿杰（男/闽南语）", "male", "adult", 0.90},
		{"Peter", "Peter 天津-李彼得（男/天津话）", "male", "adult", 0.90},
		{"Sunny", "Sunny 四川-晴儿（女/四川话）", "female", "teen", 0.90},
		{"Eric", "Eric 四川-程川（男/四川话）", "male", "adult", 0.90},
		{"Rocky", "Rocky 粤语-阿强（男/粤语）", "male", "adult", 0.90},
		{"Kiki", "Kiki 粤语-阿清（女/粤语）", "female", "adult", 0.90},
	},
	// ── 腾讯云语音合成 ───────────────────────────────────────────────
	"tencent-tts": {
		{"101001", "智言（男/标准）", "male", "adult", 0.91},
		{"101002", "智雅（女/标准）", "female", "adult", 0.91},
		{"101003", "智燕（女/温暖）", "female", "adult", 0.91},
		{"101004", "智晶（女/标准）", "female", "adult", 0.91},
		{"101005", "智嘉（男/专业）", "male", "adult", 0.91},
		{"101006", "智开（男/播音）", "male", "adult", 0.92},
		{"101008", "智浩（男/播音）", "male", "adult", 0.92},
		{"101009", "智莉（女/温暖）", "female", "adult", 0.91},
		{"101010", "智华（男/年轻）", "male", "adult", 0.90},
		{"101011", "智燃（男/活力）", "male", "adult", 0.90},
		{"101012", "智雪（女/温柔）", "female", "adult", 0.91},
		{"101013", "智希（女/活泼）", "female", "adult", 0.90},
		{"101014", "智宁（男/成熟）", "male", "adult", 0.91},
		{"101015", "智萌（童/活泼）", "neutral", "child", 0.90},
		{"101016", "智甜（女/甜美）", "female", "adult", 0.90},
		{"101017", "智蓉（女/四川话）", "female", "adult", 0.89},
		{"101050", "WeJack（英文男声）", "male", "adult", 0.90},
		{"101051", "WeRose（英文女声）", "female", "adult", 0.90},
	},
	// ── 可灵语音合成 ──────────────────────────────────────────────────
	"kling": {
		{"zh_female_story", "故事女声（中文）", "female", "adult", 0.92},
		{"zh_female_qingxin", "清新女声（中文）", "female", "adult", 0.91},
		{"zh_female_tianmei", "甜美女声（中文）", "female", "adult", 0.91},
		{"zh_female_wenrou", "温柔女声（中文）", "female", "adult", 0.91},
		{"zh_female_zhishixing", "知性女声（中文）", "female", "adult", 0.91},
		{"zh_male_story", "故事男声（中文）", "male", "adult", 0.92},
		{"zh_male_zhengpai", "正派男声（中文）", "male", "adult", 0.91},
		{"zh_male_xinwen", "新闻男声（中文）", "male", "adult", 0.91},
		{"zh_male_shuhu", "书虎男声（中文）", "male", "adult", 0.90},
		{"zh_male_qingnian", "青年男声（中文）", "male", "adult", 0.90},
		{"oversea_male1", "英文男声", "male", "adult", 0.90},
		{"oversea_female1", "英文女声", "female", "adult", 0.90},
	},
}
